Add a parameter to hide the waiting message in the GUI
gnif/LookingGlass pull request #1141
Opened 2024-11-04 14:16 UTC by RodoMa92

Just a small change to hide the popup messagebox in the UI while waiting.

2024-11-04 23:04 UTC, gnif requested changes
Looks good, a few changes to be made though.

Also please be sure to add yourself to the `AUTHORS` file, and update the documentation with the new parameter.

2024-11-04 23:04 UTC, gnif commented on client/src/main.c
> +          if (!g_params.hideWaitingMessage) {
`{` on new line please

2024-11-04 23:04 UTC, gnif commented on client/src/config.c
> +    .name           = "hideWaitingMessage",
Please change this to: `disableWaitingMessage`

2024-11-04 23:04 UTC, gnif commented on client/src/config.c
> +    .description    = "Disable the waiting message during startup",
Please change this to: `Disable the waiting for host message during startup`

2024-11-04 23:04 UTC, gnif commented on client/src/main.h
> +  bool                 hideWaitingMessage;
Change to: `disableWaitingMessage`

2024-11-05 18:43 UTC, RodoMa92 commented
It should be all good to go, now. Let me know if you need additional changes merged here.

2025-02-15 22:16 UTC, JJRcop approved these changes
Thanks for fixing the requested changes. Documentation edits were just updating the client-side params, and this appears to have been done correctly.

2025-03-24 19:36 UTC, Scrut1ny commented
@RodoMa92 In `doc/usage.rst`, adjust the `disableWaitingMessage` description and make sure the word "disable" has a "s." You could also just make it more direct: "Disables the confirmation message for a cleaner UI." Also instead of "cleaner" you could use "minimal" potentially.

2025-03-25 09:07 UTC, JJRcop commented
> @RodoMa92 In `doc/usage.rst`, adjust the `disableWaitingMessage` description and make sure the word "disable" has a "s." You could also just make it more direct: "Disables the confirmation message for a cleaner UI." Also instead of "cleaner" you could use "minimal" potentially.

usage.rst has a table produced from running `looking-glass-client --rst-help`

I definitely seem to have missed the discrepancy, so thanks, but it's as simple as rebuilding the client and running that command again

2025-06-27 23:59 UTC, rennr commented
Does anything more have to be done before this can be merged? 

It would be helpful to disable that message.

2025-06-28 03:03 UTC, gnif commented
> Does anything more have to be done before this can be merged?
> 
> It would be helpful to disable that message.



> Ready to merge this, just a conflict in AUTHORS needs correcting.

2025-06-28 06:51 UTC, RodoMa92 commented
It should be ready to merge now.

2025-06-28 07:13 UTC, gnif commented on doc/usage.rst
> +  | win:disableWaitingMessage  |       | no                     | Disables the confirmation message for a cleaner UI                                      |
The formatting here is incorrect. Please use `./looking-glass-client --rst-help` to generate the help for this documentation.

2025-06-28 07:13 UTC, gnif requested changes
Formatting issue with documentation

2025-06-28 07:17 UTC, RodoMa92 commented on doc/usage.rst
> +  | win:disableWaitingMessage  |       | no                     | Disables the confirmation message for a cleaner UI                                      |
Should be fixed now, sorry.

2025-06-28 07:25 UTC, RodoMa92 commented
> Formatting issue with documentation

Should be fixed now for good.

2025-06-28 07:25 UTC, gnif commented
Sorry but your PR should not introduce a problem and then fix it with another commit, this creates useless noise in the master repository. Please ammend your commits, squash those that are not needed, and force-push a clean set of commits for merge.

2025-06-28 15:12 UTC, RodoMa92 commented
Should be cleaned up now.

2025-06-30 04:25 UTC, merged