Optionally reenable compositor when client window loses focus
gnif/LookingGlass pull request #212
Opened 2019-11-29 14:50 UTC by thejavascriptman

This PR adds the optional `win:enableCompositorOnFocusLoss` argument to re-enable compositor if client window loses focus. 

The default value for `enableCompositorOnFocusLoss` is `false` so default behavior should be preserved, however I had to replace `NETWM_BYPASS_COMPOSITOR` with `_NET_WM_BYPASS_COMPOSITOR` as the first one was not working at all.

Please let me know if there is anything else that can be improved or if you have a better name for the new parameter 🙂

2019-11-29 23:27 UTC, gnif commented on client/src/main.c
> +  if (state.wminfo.subsystem != SDL_SYSWM_X11)
cosmetic: no need for curly braces here, please change this to the format
```
if (boolean)
  return;
```

2019-11-29 23:27 UTC, gnif commented on client/src/main.c
> +void bypassCompositor(unsigned long value)
this should be `static void` as it's only used locally, and please use a boolean, not unsigned long.

2019-11-29 23:28 UTC, gnif commented on client/src/main.c
> +          if (params.enableCompositorOnFocusLoss)
cosmetic: ditto re braces

2019-11-29 23:29 UTC, gnif commented on client/src/main.c
> +  if (state.wminfo.subsystem == SDL_SYSWM_X11)
new line before this `if` please and again no need for the braces

2019-12-01 14:56 UTC, thejavascriptman commented
Thank you for the detailed feedback.

Regarding the parameter name, do you recommend implementing an enum like
```
enum AllowCompositor
{
  NO=0,
  YES=1,
  ON_FOCUS_LOST=2
}
```

Or just use an integer and mention it's values in the readme file? e.g.
```
| win:allowCompositor |    |  0  | Allow compositor (0=no,  1=yes, 2=OnLostFocus)  |
```

2020-10-19 03:49 UTC, thejavascriptman commented
Thank you for the comments, will take a look during this week

2020-10-25 08:12 UTC, thejavascriptman commented
@gnif Please take a look and let me know if there are other changes you would like me to make.

2020-10-25 10:16 UTC, gnif requested changes
Sorry but this PR is now a complete jumble, seems you made a mistake when merging. I suggest you rebase your changes on the latest master and void merges in the future which will avoid these issues.

2021-07-22 03:15 UTC, gnif commented
As the code base has changed so much this PR doesn't make any sense anymore as it stands. Closing.

2021-07-22 03:15 UTC, closed without merging