[client] egl: force DMA copy into texture in on_frame
gnif/LookingGlass pull request #458
Opened 2021-02-07 05:10 UTC by quantum5

This commit forces the DMA'd memory to be copied into the texture in
the EGL on_frame handler. This avoids tearing when the LG host inevitably
updates the underlying memory. We need an additional copy inside the GPU,
but this is cheap compared to copying from system memory.

We could have used logic to lock the memory buffer, but that would require
performing DMA on every frame, which wastes memory bandwidth. This
manifests as reduced frame rate when moving the mouse compared to the
non-DMA implementation.

We also keep multiple EGLImages, one for each DMA fd, to avoid issues
with the OpenGL driver.

2021-02-08 22:09 UTC, gnif requested changes
Looks fine, just a few minor changes.

2021-02-08 22:09 UTC, gnif commented on client/renderers/EGL/texture.c
> +  struct {
nit: formatting
```c
struct
{
}
* dmaImages;
```

2021-02-08 22:09 UTC, gnif commented on client/renderers/EGL/texture.c
> +    size_t index = texture->dmaImageUsed++;
`const size_t`

2021-02-08 22:58 UTC, quantum5 commented on client/renderers/EGL/texture.c
> +  struct {
Fixed.

2021-02-08 22:58 UTC, quantum5 commented on client/renderers/EGL/texture.c
> +    size_t index = texture->dmaImageUsed++;
Fixed.

2021-02-09 08:49 UTC, gnif approved these changes

2021-02-09 08:52 UTC, merged