[client] add XDG Base Directory specification compliance for config file loading
gnif/LookingGlass pull request #520
Opened 2021-04-19 06:36 UTC by thomasqueirozb

…ile loading

2021-04-19 06:53 UTC, gnif commented on client/README.md
> +By default the application will load the config file in /etc/looking-glass-client.ini and then look for one user config file in the following locations
There is no need to change the wording here, please retain the list.

2021-04-19 07:02 UTC, gnif requested changes
Please see the requested changes. Also fix the commit message to a maximum width of 72 characters, ie:

`[client] config: load configuration as per XDG spec`

Also please provide a summary of the changes and the rationale behind them.

2021-04-19 07:02 UTC, gnif commented on client/src/config.c
> +    alloc_sprintf(&localFile, "%s/.looking-glass-client.ini", pw->pw_dir);
Missing free on success

2021-04-19 17:02 UTC, thomasqueirozb commented on client/src/config.c
> +  if (!load_config_from_file("/etc/looking-glass-client.ini", &err) || err)
I was just trying to replicate the previous behavior. config_load would return false if /etc/looking-glass-client.ini or ~/.looking-glass-client.ini failed to load.

https://github.com/gnif/LookingGlass/blob/30c3b399f28bdd2afb2d574a997a1dd0924fe892/client/src/config.c#L440-L445
https://github.com/gnif/LookingGlass/blob/30c3b399f28bdd2afb2d574a997a1dd0924fe892/client/src/config.c#L450-L459

2021-07-22 03:13 UTC, gnif commented
Closing this outdated PR.... note though that implementing the XDG standard is on the list for the next release.

2021-07-22 03:13 UTC, closed without merging